# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerWeatherQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.WeatherAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerWeatherQuestion", llm_response=llm_response, mode="request")
        return typing.cast(types.WeatherAnswer, __result__)

    def ExtractOpenMeteoHistoricalRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.OpenMeteoHistoricalRequest"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOpenMeteoHistoricalRequest", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.OpenMeteoHistoricalRequest"], __result__)

    def GenerateDailyBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.DailyBriefAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateDailyBrief", llm_response=llm_response, mode="request")
        return typing.cast(types.DailyBriefAnswer, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerWeatherQuestion(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.WeatherAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnswerWeatherQuestion", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.WeatherAnswer, __result__)

    def ExtractOpenMeteoHistoricalRequest(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.OpenMeteoHistoricalRequest"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractOpenMeteoHistoricalRequest", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.OpenMeteoHistoricalRequest"], __result__)

    def GenerateDailyBrief(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.DailyBriefAnswer:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateDailyBrief", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.DailyBriefAnswer, __result__)

    