# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (4)
# #########################################################################

class DailyBriefAnswer(BaseModel):
    answer: typing.Optional[str] = None

class NextHoursBriefAnswer(BaseModel):
    answer: typing.Optional[str] = None

class OpenMeteoHistoricalRequest(BaseModel):
    query_type: typing.Optional[typing.Union[typing_extensions.Literal['archive'], typing_extensions.Literal['forecast']]] = None
    start_date: typing.Optional[str] = None
    end_date: typing.Optional[str] = None
    daily: typing.List[str]
    hourly: typing.List[str]

class WeatherAnswer(BaseModel):
    answer: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
