# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    def AnswerWeatherQuestion(self, question: str,city: str,datetime: str,api_response: str,
        baml_options: BamlCallOptions = {},
    ) -> types.WeatherAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.AnswerWeatherQuestion(question=question,city=city,datetime=datetime,api_response=api_response,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="AnswerWeatherQuestion", args={
                "question": question,"city": city,"datetime": datetime,"api_response": api_response,
            })
            return typing.cast(types.WeatherAnswer, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractOpenMeteoHistoricalRequest(self, question: str,today: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.OpenMeteoHistoricalRequest"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.ExtractOpenMeteoHistoricalRequest(question=question,today=today,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractOpenMeteoHistoricalRequest", args={
                "question": question,"today": today,
            })
            return typing.cast(typing.List["types.OpenMeteoHistoricalRequest"], __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateDailyBrief(self, city: str,datetime: str,daily_data: str,
        baml_options: BamlCallOptions = {},
    ) -> types.DailyBriefAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateDailyBrief(city=city,datetime=datetime,daily_data=daily_data,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateDailyBrief", args={
                "city": city,"datetime": datetime,"daily_data": daily_data,
            })
            return typing.cast(types.DailyBriefAnswer, __result__.cast_to(types, types, stream_types, False, __runtime__))
    def GenerateNextHoursBrief(self, city: str,datetime: str,window_hours: int,hourly_data: str,
        baml_options: BamlCallOptions = {},
    ) -> types.NextHoursBriefAnswer:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            __stream__ = self.stream.GenerateNextHoursBrief(city=city,datetime=datetime,window_hours=window_hours,hourly_data=hourly_data,
                baml_options=baml_options)
            return __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = self.__options.merge_options(baml_options).call_function_sync(function_name="GenerateNextHoursBrief", args={
                "city": city,"datetime": datetime,"window_hours": window_hours,"hourly_data": hourly_data,
            })
            return typing.cast(types.NextHoursBriefAnswer, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerWeatherQuestion(self, question: str,city: str,datetime: str,api_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.WeatherAnswer, types.WeatherAnswer]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnswerWeatherQuestion", args={
            "question": question,"city": city,"datetime": datetime,"api_response": api_response,
        })
        return baml_py.BamlSyncStream[stream_types.WeatherAnswer, types.WeatherAnswer](
          __result__,
          lambda x: typing.cast(stream_types.WeatherAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.WeatherAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def ExtractOpenMeteoHistoricalRequest(self, question: str,today: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.OpenMeteoHistoricalRequest"], typing.List["types.OpenMeteoHistoricalRequest"]]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractOpenMeteoHistoricalRequest", args={
            "question": question,"today": today,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.OpenMeteoHistoricalRequest"], typing.List["types.OpenMeteoHistoricalRequest"]](
          __result__,
          lambda x: typing.cast(typing.List["stream_types.OpenMeteoHistoricalRequest"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.OpenMeteoHistoricalRequest"], x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateDailyBrief(self, city: str,datetime: str,daily_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.DailyBriefAnswer, types.DailyBriefAnswer]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateDailyBrief", args={
            "city": city,"datetime": datetime,"daily_data": daily_data,
        })
        return baml_py.BamlSyncStream[stream_types.DailyBriefAnswer, types.DailyBriefAnswer](
          __result__,
          lambda x: typing.cast(stream_types.DailyBriefAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.DailyBriefAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def GenerateNextHoursBrief(self, city: str,datetime: str,window_hours: int,hourly_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.NextHoursBriefAnswer, types.NextHoursBriefAnswer]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_sync_stream(function_name="GenerateNextHoursBrief", args={
            "city": city,"datetime": datetime,"window_hours": window_hours,"hourly_data": hourly_data,
        })
        return baml_py.BamlSyncStream[stream_types.NextHoursBriefAnswer, types.NextHoursBriefAnswer](
          __result__,
          lambda x: typing.cast(stream_types.NextHoursBriefAnswer, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.NextHoursBriefAnswer, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerWeatherQuestion(self, question: str,city: str,datetime: str,api_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerWeatherQuestion", args={
            "question": question,"city": city,"datetime": datetime,"api_response": api_response,
        }, mode="request")
        return __result__
    def ExtractOpenMeteoHistoricalRequest(self, question: str,today: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractOpenMeteoHistoricalRequest", args={
            "question": question,"today": today,
        }, mode="request")
        return __result__
    def GenerateDailyBrief(self, city: str,datetime: str,daily_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateDailyBrief", args={
            "city": city,"datetime": datetime,"daily_data": daily_data,
        }, mode="request")
        return __result__
    def GenerateNextHoursBrief(self, city: str,datetime: str,window_hours: int,hourly_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateNextHoursBrief", args={
            "city": city,"datetime": datetime,"window_hours": window_hours,"hourly_data": hourly_data,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnswerWeatherQuestion(self, question: str,city: str,datetime: str,api_response: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnswerWeatherQuestion", args={
            "question": question,"city": city,"datetime": datetime,"api_response": api_response,
        }, mode="stream")
        return __result__
    def ExtractOpenMeteoHistoricalRequest(self, question: str,today: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractOpenMeteoHistoricalRequest", args={
            "question": question,"today": today,
        }, mode="stream")
        return __result__
    def GenerateDailyBrief(self, city: str,datetime: str,daily_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateDailyBrief", args={
            "city": city,"datetime": datetime,"daily_data": daily_data,
        }, mode="stream")
        return __result__
    def GenerateNextHoursBrief(self, city: str,datetime: str,window_hours: int,hourly_data: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = self.__options.merge_options(baml_options).create_http_request_sync(function_name="GenerateNextHoursBrief", args={
            "city": city,"datetime": datetime,"window_hours": window_hours,"hourly_data": hourly_data,
        }, mode="stream")
        return __result__
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))