# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.DailyBriefAnswer": types.DailyBriefAnswer,
    "stream_types.DailyBriefAnswer": stream_types.DailyBriefAnswer,

    "types.NextHoursBriefAnswer": types.NextHoursBriefAnswer,
    "stream_types.NextHoursBriefAnswer": stream_types.NextHoursBriefAnswer,

    "types.OpenMeteoHistoricalRequest": types.OpenMeteoHistoricalRequest,
    "stream_types.OpenMeteoHistoricalRequest": stream_types.OpenMeteoHistoricalRequest,

    "types.WeatherAnswer": types.WeatherAnswer,
    "stream_types.WeatherAnswer": stream_types.WeatherAnswer,


}